<script lang="ts">
    import {
        Button,
        Card,
        Table,
        TableBody,
        TableBodyCell,
        TableBodyRow,
        TableHead,
        TableHeadCell,
        ListPlaceholder,
    } from "flowbite-svelte";
    import Spiral from "~icons/streamline/spiral-shape-solid";
    import Document from "~icons/mdi/document";
    import { onMount } from "svelte";
    import Srvbench from "$lib/sb/Srvbench";
    import Event from "./Event.svelte";

    let summaries = [
        {
            start: new Date(),
            end: new Date(),
            author: "quiquelhappy",
            messages: 300,
        },
    ];
    let messages: any[] = [];

    function addMessage(
        message: string,
        sender: string,
        medium: string,
        mediumName: string,
        channel: string | null = null,
        receiver: string | null = null,
    ) {
        messages.unshift({
            created: new Date(),
            medium: {
                type: medium,
                name: mediumName,
            },
            channel: {
                name: channel,
                receiver: receiver,
            },
            sender: sender,
            text: message,
        });
        messages = messages;
    }
    let opening = true;
    onMount(async () => {
        const socket = await Srvbench.getInstance().getCommunity()!.spectate();
        socket.addEventListener("message", async (e) => {
            const message = JSON.parse(e.data);
            if (message.type == "chat") {
                addMessage(
                    message.message,
                    message.sender?.name[0].value,
                    message.medium,
                    "default",
                    message.channel,
                    message.receiver?.name[0].value,
                );
            }
        });
        socket.addEventListener("open", () => {
            opening = false;
        });
        socket.addEventListener("error", () => {
            opening = false;
        });
    });
</script>


<!--<Card class="max-w-full flex flex-col gap-5">
    <div class="flex flex-row gap-5 items-center font-bold">
        <Spiral />
        <span> AI Summaries </span>
        <div class="grow text-right">
            <Button color="alternative">Generate</Button>
        </div>
    </div>
    <div class="border-2 rounded overflow-hidden">
        <Table>
            <TableHead>
                <TableHeadCell>Span</TableHeadCell>
                <TableHeadCell>Generated By</TableHeadCell>
                <TableHeadCell>Messages</TableHeadCell>
                <TableHeadCell>Output</TableHeadCell>
            </TableHead>
            <TableBody>
                {#each summaries as summary}
                    <TableBodyRow>
                        <TableBodyCell>
                            {String(summary.start.getHours()).padStart(
                                2,
                                "0",
                            )}:{String(summary.start.getMinutes()).padStart(
                                2,
                                "0",
                            )}-{String(summary.end.getHours()).padStart(
                                2,
                                "0",
                            )}:{String(summary.end.getMinutes()).padStart(
                                2,
                                "0",
                            )}
                        </TableBodyCell>
                        <TableBodyCell>
                            {summary.author}
                        </TableBodyCell>
                        <TableBodyCell>
                            {summary.messages} messages
                        </TableBodyCell>
                        <TableBodyCell tdClass="text-right pr-4">
                            <Button size="xs" color="alternative">
                                <Document />
                            </Button>
                        </TableBodyCell>
                    </TableBodyRow>
                {/each}
            </TableBody>
        </Table>
    </div>
</Card>-->
<Card class="max-w-full max-h-screen overflow-y-scroll">
    {#if opening}
        <ListPlaceholder divClass="max-w-full" />
    {:else}
        <div class="px-2">
            <table class="w-full">
                {#each messages as message, i}
                    {#key Number(i == 0) * message.created.getTime()}
                        <tr class:message={i == 0}>
                            <Event {message} />
                        </tr>
                    {/key}
                {/each}
            </table>
            <div class="text-center py-5" class:mt-5={messages.length>0}>
                New Messages Will Appear Above
            </div>
        </div>
    {/if}
</Card>

<style>
    table tr {
        border-bottom: 1px solid rgba(0, 0, 0, 0.1);
        vertical-align: top;
    }
    @keyframes expand {
        from {
            transform: translateY(-10%);
            opacity: 0;
        }
        to {
            transform: translateY(0);
            opacity: 1;
        }
    }
    .message {
        animation-name: expand;
        animation-duration: 200ms;
        animation-fill-mode: forwards;
    }
</style>
